# Generated by Django 3.1.4 on 2020-12-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='lastName',
        ),
    ]
