# Generated by Django 3.1.4 on 2020-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201207_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('subtitle', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=20000, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
