# Generated by Django 3.1.4 on 2020-12-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
