# Generated by Django 3.1.4 on 2020-12-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201208_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol',
            field=models.FloatField(null=True),
        ),
    ]
