# Generated by Django 3.1.4 on 2020-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_alcohol'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
