# Generated by Django 3.1.4 on 2020-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desscription',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
