# Generated by Django 3.1.4 on 2020-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_little_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='information',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
