# Generated by Django 3.1.4 on 2020-12-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201209_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
